fos_elastica:
    clients:
        default:
            hosts:
                - 'localhost:9200'

    indexes:
        cours:
            persistence:
                driver: orm
                model: App\Entity\Cour
                provider: ~
                listener: { enabled: false }
                finder: ~
                identifier: id_cours
            properties:
                titre:
                    type: text
                    analyzer: french
                description:
                    type: text
                    analyzer: french
                formateur:
                    type: text
                    analyzer: french
                niveau:
                    type: keyword
                statut:
                    type: keyword
