knp_snappy:
    pdf:
        enabled: true
        binary: 'C:\wkhtmltopdf\bin\wkhtmltopdf.exe'
        options:
            - { name: 'page-size', value: 'A4' }
            - { name: 'orientation', value: 'portrait' }
            - { name: 'margin-top', value: '10mm' }
            - { name: 'margin-bottom', value: '10mm' }
            - { name: 'margin-left', value: '10mm' }
            - { name: 'margin-right', value: '10mm' }
            - { name: 'encoding', value: 'UTF-8' }
            - { name: 'enable-local-file-access', value: true }
            - { name: 'images', value: true }