# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    admin_email: 'ayamosbeh91@gmail.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $adminEmail: '%admin_email%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Command/'

    App\Service\NotificationService:
        arguments:
            $adminEmail: '%admin_email%'

    App\Controller\AnthropicProxyController:
        arguments:
            $anthropicApiKey: '%env(ANTHROPIC_API_KEY)%'
        tags: ['controller.service_arguments']

    App\Controller\ChatbotController:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Controller\LeconController:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Controller\ChatbotLeconController:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Service\CourSearchService:
        arguments:
            $coursFinder: '@fos_elastica.finder.cours'

    App\Service\CoursIAService:
        arguments:
            $modelPath: '%kernel.project_dir%/var/ai/model.json'