parameters:
    admin_email: 'ayamosbeh91@gmail.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Command/'

    

    App\Service\ConseilIACarnetService:
        autowire: true
    App\Service\WhatsAppService:
        autowire: true